plugins {
    id "com.android.application"
}

android {
    namespace "com.swingdesk.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.swingdesk.app"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "1.1.1"
        buildConfigField "String", "DEFAULT_SERVER_URL", '"http://10.0.0.112:8787/"'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}